import React, { useEffect, useRef, useState } from "react";
import { api } from "../lib/api.js";
import { Alert, Card, Pill } from "../components/Ui.jsx";

const SUGGESTIONS = [
  "How is my form trending?",
  "How much protein should I eat today?",
  "Am I likely to skip today?",
  "How many reps have I actually done?",
];

export default function Coach() {
  const [msgs, setMsgs] = useState([
    {
      role: "coach",
      text:
        "I answer only from your logged numbers - reps, form scores, macros and " +
        "skip risk. Ask me something, or tap a suggestion below.",
      source: "rules",
    },
  ]);
  const [input, setInput] = useState("");
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState("");
  const endRef = useRef(null);

  useEffect(() => {
    endRef.current?.scrollIntoView({ behavior: "smooth", block: "nearest" });
  }, [msgs]);

  async function send(text) {
    const q = (text ?? input).trim();
    if (!q || busy) return;
    setInput("");
    setErr("");
    setMsgs((m) => [...m, { role: "you", text: q }]);
    setBusy(true);
    try {
      const res = await api.chat(q);
      setMsgs((m) => [...m, { role: "coach", text: res.reply, source: res.source }]);
    } catch (e) {
      setErr(e.message);
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="stack">
      <h1 style={{ margin: 0 }}>Coach</h1>
      <Alert>{err}</Alert>

      <Card className="pad-0">
        <div style={{ padding: "1rem", maxHeight: "60vh", overflowY: "auto" }}>
          {msgs.map((m, i) => (
            <div
              key={i}
              style={{
                display: "flex",
                justifyContent: m.role === "you" ? "flex-end" : "flex-start",
                marginBottom: ".7rem",
              }}
            >
              <div
                style={{
                  maxWidth: "min(42rem, 85%)",
                  background: m.role === "you" ? "var(--surface-2)" : "transparent",
                  border: m.role === "you" ? "none" : "1px solid var(--border)",
                  borderRadius: "var(--radius)",
                  padding: ".6rem .8rem",
                }}
              >
                <div style={{ whiteSpace: "pre-wrap" }}>{m.text}</div>
                {m.role === "coach" && m.source && (
                  <div style={{ marginTop: ".4rem" }}>
                    <Pill tone={m.source === "llm" ? "ok" : ""}>
                      {m.source === "llm" ? "LLM" : "rule-based"}
                    </Pill>
                  </div>
                )}
              </div>
            </div>
          ))}
          {busy && (
            <div className="row muted">
              <span className="spinner" /> thinking...
            </div>
          )}
          <div ref={endRef} />
        </div>

        <div style={{ borderTop: "1px solid var(--border)", padding: ".7rem 1rem" }}>
          <div className="btn-row" style={{ marginBottom: ".6rem" }}>
            {SUGGESTIONS.map((s) => (
              <button key={s} className="btn sm" onClick={() => send(s)} disabled={busy}>
                {s}
              </button>
            ))}
          </div>
          <form
            className="row"
            onSubmit={(e) => {
              e.preventDefault();
              send();
            }}
          >
            <input
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="Ask about your training or nutrition"
              style={{ flex: 1, minWidth: "12rem" }}
            />
            <button className="btn primary" disabled={busy || !input.trim()}>
              Send
            </button>
          </form>
        </div>
      </Card>

      <p className="hint">
        The coach runs on deterministic rules unless an ANTHROPIC_API_KEY is
        configured on the server, in which case replies are generated by Claude with
        your stats injected. Either way it declines medical questions - see the
        <span className="mono"> chat_service.py</span> system prompt.
      </p>
    </div>
  );
}
